### ISSUE TITLE
Er mist een mappenstructuur

### ISSUE THREAD

**Issue by GekkeBoyJeff** [Davi9898/web-app-from-scratch-2223#11]
Jouw bestanden hebben geen mappen waar ze in horen. Dit oogt als rommelig.

Probeer standaard de volgende mappen te maken:
js
images
css

in je zet je je javascript bestanden.
in images zet je je afbeeldingen
in css zet je je css file(s)

**Comment by Davi9898** [comment]
Gefixed bij de volgende push!
